S3_BUCKET = "[redacted]"

S3_PRETRAIN_PREPROCESSED_PATH = "[redacted]"

S3_FINETUNE_UNRESTRICTED_PREPROCESSED_PATH = "[redacted]"
S3_FINETUNE_RESTRICTED_PREPROCESSED_PATH = "[redacted]"

S3_EXTERNAL_VALIDATION_UNRESTRICTED_PREPROCESSED_PATH = "[redacted]"
S3_EXTERNAL_VALIDATION_RESTRICTED_PREPROCESSED_PATH = "[redacted]"

S3_ONE_HOT_PREPROCESSED_PATH = "[redacted]"
S3_ONE_HOT_EXTERNAL_VALIDATION_PREPROCESSED_PATH = "[redacted]"

S3_MODEL_OUTPUT_PATH = "[redacted]"
